/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    query ProductSingle($handle: String!) {\n      product(handle: $handle) {\n        title\n        description(truncateAt: 256)\n        seo {\n          title\n          description\n        }\n        priceRange {\n          minVariantPrice {\n            amount\n            currencyCode\n          }\n        }\n        images(first: 250) {\n          nodes {\n            id\n            url(transform: { maxHeight: 600 })\n            altText\n            width\n            height\n          }\n        }\n        options(first: 250) {\n          id\n          name\n          values\n        }\n        variants(first: 250) {\n          nodes {\n            id\n            availableForSale\n            priceV2 {\n              amount\n              currencyCode\n            }\n            selectedOptions {\n              name\n              value\n            }\n            image {\n              id\n            }\n          }\n        }\n      }\n    }\n  ": typeof types.ProductSingleDocument,
    "\n    query Collections($first: Int!) {\n      collections(first: $first) {\n        edges {\n          node {\n            id\n            title\n            handle\n            description\n            image {\n              url\n              altText\n            }\n            products(first: 5) {\n              edges {\n                node {\n                  id\n                  title\n                  handle\n                  priceRange {\n                    minVariantPrice {\n                      amount\n                      currencyCode\n                    }\n                  }\n                  featuredImage {\n                    url\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": typeof types.CollectionsDocument,
    "\n    query ProductList($first: Int!, $after: String) {\n      products(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            handle\n            title\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            featuredImage {\n              url(transform: { maxWidth: 500 })\n              altText\n              width\n              height\n            }\n            variants(first: 1) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": typeof types.ProductListDocument,
    "\n    query ProductsByCategory($category: String!, $first: Int!, $after: String) {\n      products(first: $first, after: $after, query: $category) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            handle\n            title\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            featuredImage {\n              url(transform: { maxWidth: 500 })\n              altText\n              width\n              height\n            }\n            variants(first: 1) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": typeof types.ProductsByCategoryDocument,
    "\n    query ProductsByCollection($handle: String!, $first: Int!, $after: String) {\n      collection(handle: $handle) {\n        title\n        description\n        products(first: $first, after: $after) {\n          pageInfo {\n            hasNextPage\n          }\n          edges {\n            cursor\n            node {\n              handle\n              title\n              priceRange {\n                minVariantPrice {\n                  amount\n                  currencyCode\n                }\n              }\n              featuredImage {\n                url(transform: { maxWidth: 500 })\n                altText\n                width\n                height\n              }\n              variants(first: 1) {\n                edges {\n                  node {\n                    id\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": typeof types.ProductsByCollectionDocument,
};
const documents: Documents = {
    "\n    query ProductSingle($handle: String!) {\n      product(handle: $handle) {\n        title\n        description(truncateAt: 256)\n        seo {\n          title\n          description\n        }\n        priceRange {\n          minVariantPrice {\n            amount\n            currencyCode\n          }\n        }\n        images(first: 250) {\n          nodes {\n            id\n            url(transform: { maxHeight: 600 })\n            altText\n            width\n            height\n          }\n        }\n        options(first: 250) {\n          id\n          name\n          values\n        }\n        variants(first: 250) {\n          nodes {\n            id\n            availableForSale\n            priceV2 {\n              amount\n              currencyCode\n            }\n            selectedOptions {\n              name\n              value\n            }\n            image {\n              id\n            }\n          }\n        }\n      }\n    }\n  ": types.ProductSingleDocument,
    "\n    query Collections($first: Int!) {\n      collections(first: $first) {\n        edges {\n          node {\n            id\n            title\n            handle\n            description\n            image {\n              url\n              altText\n            }\n            products(first: 5) {\n              edges {\n                node {\n                  id\n                  title\n                  handle\n                  priceRange {\n                    minVariantPrice {\n                      amount\n                      currencyCode\n                    }\n                  }\n                  featuredImage {\n                    url\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": types.CollectionsDocument,
    "\n    query ProductList($first: Int!, $after: String) {\n      products(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            handle\n            title\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            featuredImage {\n              url(transform: { maxWidth: 500 })\n              altText\n              width\n              height\n            }\n            variants(first: 1) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": types.ProductListDocument,
    "\n    query ProductsByCategory($category: String!, $first: Int!, $after: String) {\n      products(first: $first, after: $after, query: $category) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            handle\n            title\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            featuredImage {\n              url(transform: { maxWidth: 500 })\n              altText\n              width\n              height\n            }\n            variants(first: 1) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": types.ProductListDocument, // Using ProductListDocument as fallback
    "\n    query ProductsByCollection($handle: String!, $first: Int!, $after: String) {\n      collection(handle: $handle) {\n        title\n        description\n        products(first: $first, after: $after) {\n          pageInfo {\n            hasNextPage\n          }\n          edges {\n            cursor\n            node {\n              handle\n              title\n              priceRange {\n                minVariantPrice {\n                  amount\n                  currencyCode\n                }\n              }\n              featuredImage {\n                url(transform: { maxWidth: 500 })\n                altText\n                width\n                height\n              }\n              variants(first: 1) {\n                edges {\n                  node {\n                    id\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ": types.CollectionsDocument, // Using CollectionsDocument as fallback
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductSingle($handle: String!) {\n      product(handle: $handle) {\n        title\n        description(truncateAt: 256)\n        seo {\n          title\n          description\n        }\n        priceRange {\n          minVariantPrice {\n            amount\n            currencyCode\n          }\n        }\n        images(first: 250) {\n          nodes {\n            id\n            url(transform: { maxHeight: 600 })\n            altText\n            width\n            height\n          }\n        }\n        options(first: 250) {\n          id\n          name\n          values\n        }\n        variants(first: 250) {\n          nodes {\n            id\n            availableForSale\n            priceV2 {\n              amount\n              currencyCode\n            }\n            selectedOptions {\n              name\n              value\n            }\n            image {\n              id\n            }\n          }\n        }\n      }\n    }\n  "): typeof import('./graphql').ProductSingleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query Collections($first: Int!) {\n      collections(first: $first) {\n        edges {\n          node {\n            id\n            title\n            handle\n            description\n            image {\n              url\n              altText\n            }\n            products(first: 5) {\n              edges {\n                node {\n                  id\n                  title\n                  handle\n                  priceRange {\n                    minVariantPrice {\n                      amount\n                      currencyCode\n                    }\n                  }\n                  featuredImage {\n                    url\n                    altText\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  "): typeof import('./graphql').CollectionsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductList($first: Int!, $after: String) {\n      products(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            handle\n            title\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            featuredImage {\n              url(transform: { maxWidth: 500 })\n              altText\n              width\n              height\n            }\n            variants(first: 1) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  "): typeof import('./graphql').ProductListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductsByCategory($category: String!, $first: Int!, $after: String) {\n      products(first: $first, after: $after, query: $category) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            handle\n            title\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            featuredImage {\n              url(transform: { maxWidth: 500 })\n              altText\n              width\n              height\n            }\n            variants(first: 1) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  "): typeof import('./graphql').ProductListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ProductsByCollection($handle: String!, $first: Int!, $after: String) {\n      collection(handle: $handle) {\n        title\n        description\n        products(first: $first, after: $after) {\n          pageInfo {\n            hasNextPage\n          }\n          edges {\n            cursor\n            node {\n              handle\n              title\n              priceRange {\n                minVariantPrice {\n                  amount\n                  currencyCode\n                }\n              }\n              featuredImage {\n                url(transform: { maxWidth: 500 })\n                altText\n                width\n                height\n              }\n              variants(first: 1) {\n                edges {\n                  node {\n                    id\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  "): typeof import('./graphql').CollectionsDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
